### ISSUE TITLE
Error message panel can't be discarded once displayed

### ISSUE THREAD

**Issue by abe33** [atom/update-package-dependencies#10]
I just encountered it as I was trying the command (I mostly use `apm update` these days). I got an error during the update, and got this message displayed: 

![new_html_haml_-__users_cedric_development_ruby_bigard-recrute_-_atom](https://cloud.githubusercontent.com/assets/247140/10967296/c5d2b948-83b9-11e5-9072-1cde4d720439.png)

The first problem is that once this message appears there's no way to make it disappears (except yb removing it from the DOM using the devtools).

The second problem is that the message is probably a bit light, having some kind of information about the source of the issue would be better (to know if it's the command that failed, a network error, etc.)

**Comment by abe33** [comment]
In fact the main issue here is that the command should not attempt to run `apm install` if there's no `package.json` file in the current project.

**Comment by idleberg** [comment]
Actually, it's the same for me with successfull updates. Please merge #9!

**Comment by uhlissuh** [comment]
Yea, this problem still exists! https://github.com/atom/update-package-dependencies/pull/9 this would be a good fix.
